<?php

/**
 * This is the model base class for the table "conteudo_categorias".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConteudoCategorias".
 *
 * Columns in table "conteudo_categorias" available as properties of the model,
 * followed by relations of table "conteudo_categorias" available as properties of the model.
 *
 * @property integer $id
 * @property string $macro
 * @property string $titulo
 * @property string $slug
 *
 * @property Conteudos[] $conteudoses
 */
abstract class BaseConteudoCategorias extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'conteudo_categorias';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConteudoCategorias|ConteudoCategoriases', $n);
	}

	public static function representingColumn() {
		return 'macro';
	}

	public function rules() {
		return array(
			array('titulo, slug', 'required'),
			array('macro', 'length', 'max'=>1),
			array('titulo, slug', 'length', 'max'=>45),
			array('macro', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, macro, titulo, slug', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'conteudoses' => array(self::HAS_MANY, 'Conteudos', 'conteudo_categorias_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'macro' => Yii::t('app', 'Macro'),
			'titulo' => Yii::t('app', 'Titulo'),
			'slug' => Yii::t('app', 'Slug'),
			'conteudoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('macro', $this->macro, true);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('slug', $this->slug, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}