<?php

/**
 * This is the model base class for the table "log_logins".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LogLogins".
 *
 * Columns in table "log_logins" available as properties of the model,
 * followed by relations of table "log_logins" available as properties of the model.
 *
 * @property integer $id
 * @property integer $usuarios_id
 * @property string $date
 * @property string $ip
 *
 * @property Usuarios $usuarios
 */
abstract class BaseLogLogins extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'log_logins';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LogLogins|LogLogins', $n);
	}

	public static function representingColumn() {
		return 'date';
	}

	public function rules() {
		return array(
			array('usuarios_id, date, ip', 'required'),
			array('usuarios_id', 'numerical', 'integerOnly'=>true),
			array('ip', 'length', 'max'=>18),
			array('id, usuarios_id, date, ip', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'usuarios_id' => null,
			'date' => Yii::t('app', 'Date'),
			'ip' => Yii::t('app', 'Ip'),
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('usuarios_id', $this->usuarios_id);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('ip', $this->ip, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}