<?php

/**
 * This is the model base class for the table "embarcacao_fabricantes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacaoFabricantes".
 *
 * Columns in table "embarcacao_fabricantes" available as properties of the model,
 * followed by relations of table "embarcacao_fabricantes" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacao_macros_id
 * @property string $logo
 * @property string $titulo
 * @property string $slug
 * @property integer $status
 *
 * @property EmbarcacaoMacros $embarcacaoMacros
 * @property EmbarcacaoModelos[] $embarcacaoModeloses
 * @property EmbarcacaoModelosEditavel[] $embarcacaoModelosEditavels
 */
abstract class BaseEmbarcacaoFabricantes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacao_fabricantes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacaoFabricantes|EmbarcacaoFabricantes', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('embarcacao_macros_id, titulo, slug', 'required'),
			array('embarcacao_macros_id, status', 'numerical', 'integerOnly'=>true),
			array('logo, slug', 'length', 'max'=>100),
			array('titulo', 'length', 'max'=>45),
			array('logo, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacao_macros_id, logo, titulo, slug, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacaoMacros' => array(self::BELONGS_TO, 'EmbarcacaoMacros', 'embarcacao_macros_id'),
			'embarcacaoModeloses' => array(self::HAS_MANY, 'EmbarcacaoModelos', 'embarcacao_fabricantes_id'),
			'embarcacaoModelosEditavels' => array(self::HAS_MANY, 'EmbarcacaoModelosEditavel', 'embarcacao_fabricantes_id'),
			'embarcacoes' => array(self::HAS_MANY, 'Embarcacoes', 'embarcacao_modelos_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacao_macros_id' => null,
			'logo' => Yii::t('app', 'Logo'),
			'titulo' => Yii::t('app', 'Titulo'),
			'slug' => Yii::t('app', 'Slug'),
			'status' => Yii::t('app', 'Status'),
			'embarcacaoMacros' => null,
			'embarcacaoModeloses' => null,
			'embarcacaoModelosEditavels' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);
		$criteria->compare('logo', $this->logo, true);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}