<?php

/**
 * This is the model base class for the table "motor_tipos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MotorTipos".
 *
 * Columns in table "motor_tipos" available as properties of the model,
 * followed by relations of table "motor_tipos" available as properties of the model.
 *
 * @property integer $id
 * @property string $titulo
 * @property string $slug
 * @property integer $status
 *
 * @property MotorAnuncio[] $motorAnuncios
 * @property MotorAnuncioPreview[] $motorAnuncioPreviews
 * @property MotorModelos[] $motorModeloses
 */
abstract class BaseMotorTipos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'motor_tipos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MotorTipos|MotorTiposes', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>45),
			array('slug', 'safe'),
			array('slug, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, titulo, slug, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'motorAnuncios' => array(self::HAS_MANY, 'MotorAnuncio', 'motor_tipos_id'),
			'motorAnuncioPreviews' => array(self::HAS_MANY, 'MotorAnuncioPreview', 'motor_tipos_id'),
			'motorModeloses' => array(self::HAS_MANY, 'MotorModelos', 'motor_tipos_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'slug' => Yii::t('app', 'Slug'),
			'status' => Yii::t('app', 'Status'),
			'motorAnuncios' => null,
			'motorAnuncioPreviews' => null,
			'motorModeloses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}