<?php

/**
 * This is the model base class for the table "log_acoes_admin".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LogAcoesAdmin".
 *
 * Columns in table "log_acoes_admin" available as properties of the model,
 * followed by relations of table "log_acoes_admin" available as properties of the model.
 *
 * @property integer $username
 * @property string $ipaddress
 * @property string $logtime
 * @property string $controller
 * @property string $action
 * @property string $details
 * @property integer $id
 *
 * @property Usuarios $username0
 */
abstract class BaseLogAcoesAdmin extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'log_acoes_admin';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LogAcoesAdmin|LogAcoesAdmins', $n);
	}

	public static function representingColumn() {
		return 'ipaddress';
	}

	public function rules() {
		return array(
			array('username, ipaddress, logtime', 'required'),
			array('username', 'numerical', 'integerOnly'=>true),
			array('ipaddress', 'length', 'max'=>50),
			array('controller, action', 'length', 'max'=>255),
			array('details', 'safe'),
			array('controller, action, details', 'default', 'setOnEmpty' => true, 'value' => null),
			array('username, ipaddress, logtime, controller, action, details, id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'username'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'username' => null,
			'ipaddress' => Yii::t('app', 'Ipaddress'),
			'logtime' => Yii::t('app', 'Logtime'),
			'controller' => Yii::t('app', 'Controller'),
			'action' => Yii::t('app', 'Action'),
			'details' => Yii::t('app', 'Details'),
			'id' => Yii::t('app', 'ID'),
			'username0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('username', $this->username);
		$criteria->compare('ipaddress', $this->ipaddress, true);
		$criteria->compare('logtime', $this->logtime, true);
		$criteria->compare('controller', $this->controller, true);
		$criteria->compare('action', $this->action, true);
		$criteria->compare('details', $this->details, true);
		$criteria->compare('id', $this->id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}