<?php

/**
 * This is the model base class for the table "contatos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contatos".
 *
 * Columns in table "contatos" available as properties of the model,
 * followed by relations of table "contatos" available as properties of the model.
 *
 * @property string $id
 * @property integer $usuarios_id_rem
 * @property integer $embarcacoes_id
 * @property string $nome_rem
 * @property string $email_rem
 * @property string $mensagem
 * @property string $data
 * @property string $email_dest
 * @property string $tipo
 * @property string $telefone_rem
 * @property integer $empresas_id
 * @property integer $status
 * @property integer $usuarios_id_dest
 * @property string $data_do_titulo
 * @property string $titulo_mensagem
 * @property string $palavras_chaves
 *
 * @property Embarcacoes $embarcacoes
 * @property Usuarios $usuariosIdRem
 * @property Usuarios $usuariosIdDest
 * @property Empresas $empresas
 */
abstract class BaseContatos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contatos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Contatos|Contatoses', $n);
	}

	public static function representingColumn() {
		return 'data';
	}

	public function rules() {
		return array(
			array('data, email_dest', 'required'),
			array('usuarios_id_rem, embarcacoes_id, motor_anuncio_id, empresas_id, status, usuarios_id_dest', 'numerical', 'integerOnly'=>true),
			array('nome_rem, email_rem, email_dest', 'length', 'max'=>200),
			array('tipo', 'length', 'max'=>1),
			array('telefone_rem', 'length', 'max'=>30),
			array('titulo_mensagem', 'length', 'max'=>10000),
			array('palavras_chaves', 'length', 'max'=>1500),
			array('mensagem, data_do_titulo', 'safe'),
			array('usuarios_id_rem, embarcacoes_id, motor_anuncio_id, nome_rem, email_rem, mensagem, tipo, telefone_rem, empresas_id, status, usuarios_id_dest, data_do_titulo, titulo_mensagem, palavras_chaves', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, usuarios_id_rem, embarcacoes_id, motor_anuncio_id, nome_rem, email_rem, mensagem, data, email_dest, tipo, telefone_rem, empresas_id, status, usuarios_id_dest, data_do_titulo, titulo_mensagem, palavras_chaves', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
			'motores' => array(self::BELONGS_TO, 'MotorAnuncio', 'motor_anuncio_id'),
			'usuariosIdRem' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id_rem'),
			'usuariosIdDest' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id_dest'),
			'empresas' => array(self::BELONGS_TO, 'Empresas', 'empresas_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'usuarios_id_rem' => null,
			'embarcacoes_id' => null,
			'nome_rem' => Yii::t('app', 'Nome Rem'),
			'email_rem' => Yii::t('app', 'Email Rem'),
			'mensagem' => Yii::t('app', 'Mensagem'),
			'data' => Yii::t('app', 'Data'),
			'email_dest' => Yii::t('app', 'Email Dest'),
			'tipo' => Yii::t('app', 'Tipo'),
			'telefone_rem' => Yii::t('app', 'Telefone Rem'),
			'empresas_id' => null,
			'status' => Yii::t('app', 'Status'),
			'usuarios_id_dest' => null,
			'data_do_titulo' => Yii::t('app', 'Data Do Titulo'),
			'titulo_mensagem' => Yii::t('app', 'Titulo Mensagem'),
			'palavras_chaves' => Yii::t('app', 'Palavras Chaves'),
			'embarcacoes' => null,
			'usuariosIdRem' => null,
			'usuariosIdDest' => null,
			'empresas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('usuarios_id_rem', $this->usuarios_id_rem);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('motor_anuncio_id', $this->motor_anuncio_id);
		$criteria->compare('nome_rem', $this->nome_rem, true);
		$criteria->compare('email_rem', $this->email_rem, true);
		$criteria->compare('mensagem', $this->mensagem, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('email_dest', $this->email_dest, true);
		$criteria->compare('tipo', $this->tipo, true);
		$criteria->compare('telefone_rem', $this->telefone_rem, true);
		$criteria->compare('empresas_id', $this->empresas_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('usuarios_id_dest', $this->usuarios_id_dest);
		$criteria->compare('data_do_titulo', $this->data_do_titulo, true);
		$criteria->compare('titulo_mensagem', $this->titulo_mensagem, true);
		$criteria->compare('palavras_chaves', $this->palavras_chaves, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}