<?php

/**
 * This is the model base class for the table "empresas_seo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmpresasSeo".
 *
 * Columns in table "empresas_seo" available as properties of the model,
 * followed by relations of table "empresas_seo" available as properties of the model.
 *
 * @property integer $id
 * @property integer $empresas_id
 * @property integer $empresa_categorias_id
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property integer $follow
 * @property integer $index
 *
 * @property Empresas $empresas
 * @property EmpresaCategorias $empresaCategorias
 */
abstract class BaseEmpresasSeo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresas_seo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmpresasSeo|EmpresasSeos', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('empresas_id, empresa_categorias_id, follow, index', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>65),
			array('description', 'length', 'max'=>150),
			array('keywords', 'length', 'max'=>250),
			array('empresas_id, empresa_categorias_id, title, description, keywords, follow, index', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, empresas_id, empresa_categorias_id, title, description, keywords, follow, index', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empresas' => array(self::BELONGS_TO, 'Empresas', 'empresas_id'),
			'empresaCategorias' => array(self::BELONGS_TO, 'EmpresaCategorias', 'empresa_categorias_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'empresas_id' => null,
			'empresa_categorias_id' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'keywords' => Yii::t('app', 'Keywords'),
			'follow' => Yii::t('app', 'Follow'),
			'index' => Yii::t('app', 'Index'),
			'empresas' => null,
			'empresaCategorias' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('empresas_id', $this->empresas_id);
		$criteria->compare('empresa_categorias_id', $this->empresa_categorias_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keywords', $this->keywords, true);
		$criteria->compare('follow', $this->follow);
		$criteria->compare('index', $this->index);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}