<?php

/**
 * This is the model base class for the table "seo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Seo".
 *
 * Columns in table "seo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $url
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property integer $follow
 * @property integer $index
 * @property string $canonical
 *
 */
abstract class BaseSeo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'seo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Seo|Seos', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('url', 'required'),
			array('follow, index', 'numerical', 'integerOnly'=>true),
			array('url, keywords', 'length', 'max'=>250),
			array('title', 'length', 'max'=>65),
			array('canonical', 'length', 'max'=>255),
			array('description', 'safe'),
			array('title, description, keywords, follow, index, canonical', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, url, title, description, keywords, follow, index, canonical', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'url' => Yii::t('app', 'Url'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'keywords' => Yii::t('app', 'Keywords'),
			'follow' => Yii::t('app', 'Follow'),
			'index' => Yii::t('app', 'Index'),
			'canonical' => Yii::t('app', 'Canonical'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('url', preg_replace('#^https?://#', '', $this->url), true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keywords', $this->keywords, true);
		$criteria->compare('follow', $this->follow);
		$criteria->compare('index', $this->index);
		$criteria->compare('canonical', $this->canonical, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}