<?php

/**
 * This is the model base class for the table "planos_usuarios_renovados".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanosUsuariosRenovados".
 *
 * Columns in table "planos_usuarios_renovados" available as properties of the model,
 * followed by relations of table "planos_usuarios_renovados" available as properties of the model.
 *
 * @property integer $id
 * @property integer $plano_usuarios_id_atual
 * @property integer $plano_usuarios_id_renovado
 * @property integer $status
 * @property string $dataregistro
 *
 * @property PlanoUsuarios $planoUsuariosIdRenovado
 * @property PlanoUsuarios $planoUsuariosIdAtual
 */
abstract class BasePlanosUsuariosRenovados extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'planos_usuarios_renovados';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PlanosUsuariosRenovados|PlanosUsuariosRenovadoses', $n);
	}

	public static function representingColumn() {
		return 'dataregistro';
	}

	public function rules() {
		return array(
			array('plano_usuarios_id_atual, plano_usuarios_id_renovado, status, dataregistro', 'required'),
			array('plano_usuarios_id_atual, plano_usuarios_id_renovado, status', 'numerical', 'integerOnly'=>true),
			array('id, plano_usuarios_id_atual, plano_usuarios_id_renovado, status, dataregistro', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'planoUsuariosIdRenovado' => array(self::BELONGS_TO, 'PlanoUsuarios', 'plano_usuarios_id_renovado'),
			'planoUsuariosIdAtual' => array(self::BELONGS_TO, 'PlanoUsuarios', 'plano_usuarios_id_atual'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'plano_usuarios_id_atual' => null,
			'plano_usuarios_id_renovado' => null,
			'status' => Yii::t('app', 'Status'),
			'dataregistro' => Yii::t('app', 'Dataregistro'),
			'planoUsuariosIdRenovado' => null,
			'planoUsuariosIdAtual' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('plano_usuarios_id_atual', $this->plano_usuarios_id_atual);
		$criteria->compare('plano_usuarios_id_renovado', $this->plano_usuarios_id_renovado);
		$criteria->compare('status', $this->status);
		$criteria->compare('dataregistro', $this->dataregistro, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}