<?php

/**
 * This is the model base class for the table "bombarcoshop_codigos_descontos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BombarcoshopDescontos".
 *
 * Columns in table "bombarcoshop_codigos_descontos" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $id_produto
 * @property string $codigo
 * @property integer $porcentagem_desconto
 * @property string $data_inicio
 * @property string $data_fim
 * @property integer $status
 *
 */
abstract class BaseBombarcoshopDescontos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bombarcoshop_codigos_descontos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BombarcoshopDescontos|BombarcoshopDescontoses', $n);
	}

	public static function representingColumn() {
		return 'codigo';
	}

	public function rules() {
		return array(
			array('id_produto, codigo, qtde_codigos, porcentagem_desconto, data_inicio, data_fim', 'required'),
			array('id_produto, porcentagem_desconto, qtde_codigos, status', 'numerical', 'integerOnly'=>true),
			array('codigo', 'length', 'max'=>120),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_produto, codigo, qtde_codigos, porcentagem_desconto, data_inicio, data_fim, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_produto' => Yii::t('app', 'Id Produto'),
			'codigo' => Yii::t('app', 'Codigo'),
			'porcentagem_desconto' => Yii::t('app', 'Porcentagem Desconto'),
			'data_inicio' => Yii::t('app', 'Data Inicio'),
			'data_fim' => Yii::t('app', 'Data Fim'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_produto', $this->id_produto);
		$criteria->compare('codigo', $this->codigo, true);
		$criteria->compare('porcentagem_desconto', $this->porcentagem_desconto);
		$criteria->compare('data_inicio', $this->data_inicio, true);
		$criteria->compare('data_fim', $this->data_fim, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}