<?php

/**
 * This is the model base class for the table "embarcacoes_editadas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacoesEditadas".
 *
 * Columns in table "embarcacoes_editadas" available as properties of the model,
 * followed by relations of table "embarcacoes_editadas" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property string $tipo_dado
 * @property integer $plano_usuariosid
 *
 * @property Embarcacoes $embarcacoes
 * @property PlanoUsuarios $planoUsuarios
 */
abstract class BaseEmbarcacoesEditadas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacoes_editadas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacoesEditadas|EmbarcacoesEditadases', $n);
	}

	public static function representingColumn() {
		return 'tipo_dado';
	}

	public function rules() {
		return array(
			array('embarcacoes_id, plano_usuariosid', 'numerical', 'integerOnly'=>true),
			array('tipo_dado', 'length', 'max'=>45),
			array('embarcacoes_id, tipo_dado, plano_usuariosid', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, tipo_dado, plano_usuariosid', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
			'planoUsuarios' => array(self::BELONGS_TO, 'PlanoUsuarios', 'plano_usuariosid'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'tipo_dado' => Yii::t('app', 'Tipo Dado'),
			'plano_usuariosid' => null,
			'embarcacoes' => null,
			'planoUsuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('tipo_dado', $this->tipo_dado, true);
		$criteria->compare('plano_usuariosid', $this->plano_usuariosid);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}