<?php

/**
 * This is the model base class for the table "agenda_imagens".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AgendaImagens".
 *
 * Columns in table "agenda_imagens" available as properties of the model,
 * followed by relations of table "agenda_imagens" available as properties of the model.
 *
 * @property integer $id
 * @property integer $agendas_id
 * @property string $titulo
 * @property string $imagem
 *
 * @property Agendas $agendas
 */
abstract class BaseAgendaImagens extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'agenda_imagens';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AgendaImagens|AgendaImagens', $n);
	}

	public static function representingColumn() {
		return 'imagem';
	}

	public function rules() {
		return array(
			array('agendas_id, imagem', 'required'),
			array('agendas_id', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>45),
			array('imagem', 'length', 'max'=>150),
			array('titulo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, agendas_id, titulo, imagem', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agendas' => array(self::BELONGS_TO, 'Agendas', 'agendas_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'agendas_id' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'imagem' => Yii::t('app', 'Imagem'),
			'agendas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('agendas_id', $this->agendas_id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('imagem', $this->imagem, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}