<?php

/**
 * This is the model base class for the table "embarcacao_seo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacaoSeo".
 *
 * Columns in table "embarcacao_seo" available as properties of the model,
 * followed by relations of table "embarcacao_seo" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property integer $follow
 * @property integer $index
 *
 * @property Embarcacoes $embarcacoes
 */
abstract class BaseEmbarcacaoSeo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacao_seo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacaoSeo|EmbarcacaoSeos', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('embarcacoes_id', 'required'),
			array('embarcacoes_id, follow, index', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>65),
			array('description', 'length', 'max'=>150),
			array('keywords', 'length', 'max'=>250),
			array('title, description, keywords, follow, index', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, title, description, keywords, follow, index', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'keywords' => Yii::t('app', 'Keywords'),
			'follow' => Yii::t('app', 'Follow'),
			'index' => Yii::t('app', 'Index'),
			'embarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keywords', $this->keywords, true);
		$criteria->compare('follow', $this->follow);
		$criteria->compare('index', $this->index);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}