<?php

/**
 * This is the model base class for the table "embarcacoes_has_embarcacao_recursos_adicionais".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacoesHasEmbarcacaoRecursosAdicionais".
 *
 * Columns in table "embarcacoes_has_embarcacao_recursos_adicionais" available as properties of the model,
 * followed by relations of table "embarcacoes_has_embarcacao_recursos_adicionais" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property integer $embarcacao_recursos_adicionais_id
 * @property integer $status
 *
 * @property Embarcacoes $embarcacoes
 * @property EmbarcacaoRecursosAdicionais $embarcacaoRecursosAdicionais
 */
abstract class BaseEmbarcacoesHasEmbarcacaoRecursosAdicionais extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacoes_has_embarcacao_recursos_adicionais';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacoesHasEmbarcacaoRecursosAdicionais|EmbarcacoesHasEmbarcacaoRecursosAdicionaises', $n);
	}

	public static function representingColumn() {
		return array(
			'id',
			'embarcacoes_id',
			'embarcacao_recursos_adicionais_id',
		);
	}

	public function rules() {
		return array(
			array('embarcacoes_id, embarcacao_recursos_adicionais_id', 'required'),
			array('embarcacoes_id, embarcacao_recursos_adicionais_id, status', 'numerical', 'integerOnly'=>true),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, embarcacao_recursos_adicionais_id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
			'embarcacaoRecursosAdicionais' => array(self::BELONGS_TO, 'EmbarcacaoRecursosAdicionais', 'embarcacao_recursos_adicionais_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'embarcacao_recursos_adicionais_id' => null,
			'status' => Yii::t('app', 'Status'),
			'embarcacoes' => null,
			'embarcacaoRecursosAdicionais' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('embarcacao_recursos_adicionais_id', $this->embarcacao_recursos_adicionais_id);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}