<?php

/**
 * This is the model base class for the table "empresa_categorias".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmpresaCategorias".
 *
 * Columns in table "empresa_categorias" available as properties of the model,
 * followed by relations of table "empresa_categorias" available as properties of the model.
 *
 * @property integer $id
 * @property string $titulo
 * @property string $slug
 *
 * @property Empresas[] $empresases
 */
abstract class BaseEmpresaCategorias extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa_categorias';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmpresaCategorias|EmpresaCategoriases', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo, slug', 'required'),
			array('titulo, slug', 'length', 'max'=>150),
			array('id, titulo, slug', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empresases' => array(self::HAS_MANY, 'Empresas', 'empresa_categorias_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'slug' => Yii::t('app', 'Slug'),
			'empresases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('slug', $this->slug, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}