<?php

/**
 * This is the model base class for the table "comparador".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comparador".
 *
 * Columns in table "comparador" available as properties of the model,
 * followed by relations of table "comparador" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property integer $usuarios_id
 * @property string $dataregistro
 * @property integer $status
 * @property string $sessaotoken
 *
 * @property Embarcacoes $embarcacoes
 * @property Usuarios $usuarios
 */
abstract class BaseComparador extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comparador';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comparador|Comparadors', $n);
	}

	public static function representingColumn() {
		return 'sessaotoken';
	}

	public function rules() {
		return array(
			array('sessaotoken', 'required'),
			array('embarcacoes_id, usuarios_id, status', 'numerical', 'integerOnly'=>true),
			array('sessaotoken', 'length', 'max'=>150),
			array('dataregistro', 'safe'),
			array('embarcacoes_id, usuarios_id, dataregistro, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, usuarios_id, dataregistro, status, sessaotoken', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'usuarios_id' => null,
			'dataregistro' => Yii::t('app', 'Dataregistro'),
			'status' => Yii::t('app', 'Status'),
			'sessaotoken' => Yii::t('app', 'Sessaotoken'),
			'embarcacoes' => null,
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('usuarios_id', $this->usuarios_id);
		$criteria->compare('dataregistro', $this->dataregistro, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('sessaotoken', $this->sessaotoken, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}