<?php

/**
 * This is the model base class for the table "conteudo_imagens".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConteudoImagens".
 *
 * Columns in table "conteudo_imagens" available as properties of the model,
 * followed by relations of table "conteudo_imagens" available as properties of the model.
 *
 * @property integer $id
 * @property integer $conteudos_id
 * @property string $imagem
 *
 * @property Conteudos $conteudos
 */
abstract class BaseConteudoImagens extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'conteudo_imagens';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConteudoImagens|ConteudoImagens', $n);
	}

	public static function representingColumn() {
		return 'imagem';
	}

	public function rules() {
		return array(
			array('conteudos_id', 'required'),
			array('conteudos_id', 'numerical', 'integerOnly'=>true),
			array('imagem', 'length', 'max'=>150),
			array('id, conteudos_id, imagem', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'conteudos' => array(self::BELONGS_TO, 'Conteudos', 'conteudos_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'conteudos_id' => null,
			'imagem' => Yii::t('app', 'Imagem'),
			'conteudos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('conteudos_id', $this->conteudos_id);
		$criteria->compare('imagem', $this->imagem, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}