<?php

/**
 * This is the model base class for the table "motor_imagens_preview".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MotorImagensPreview".
 *
 * Columns in table "motor_imagens_preview" available as properties of the model,
 * followed by relations of table "motor_imagens_preview" available as properties of the model.
 *
 * @property integer $id
 * @property integer $motor_anuncio_preview_id
 * @property string $imagem
 * @property integer $ordem
 * @property integer $status
 *
 * @property MotorAnuncioPreview $motorAnuncioPreview
 */
abstract class BaseMotorImagensPreview extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'motor_imagens_preview';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MotorImagensPreview|MotorImagensPreviews', $n);
	}

	public static function representingColumn() {
		return 'imagem';
	}

	public function rules() {
		return array(
			array('motor_anuncio_preview_id, ordem, status', 'numerical', 'integerOnly'=>true),
			array('imagem', 'safe'),
			array('motor_anuncio_preview_id, imagem, ordem, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, motor_anuncio_preview_id, imagem, ordem, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'motorAnuncioPreview' => array(self::BELONGS_TO, 'MotorAnuncioPreview', 'motor_anuncio_preview_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'motor_anuncio_preview_id' => null,
			'imagem' => Yii::t('app', 'Imagem'),
			'ordem' => Yii::t('app', 'Ordem'),
			'status' => Yii::t('app', 'Status'),
			'motorAnuncioPreview' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('motor_anuncio_preview_id', $this->motor_anuncio_preview_id);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('ordem', $this->ordem);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}