<?php

/**
 * This is the model base class for the table "embarcacoes_favoritas_usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacoesFavoritasUsuario".
 *
 * Columns in table "embarcacoes_favoritas_usuario" available as properties of the model,
 * followed by relations of table "embarcacoes_favoritas_usuario" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id_embarcacao
 * @property integer $usuarios_id
 *
 * @property Embarcacoes $embarcacoesIdEmbarcacao
 * @property Usuarios $usuarios
 */
abstract class BaseEmbarcacoesFavoritasUsuario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacoes_favoritas_usuario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacoesFavoritasUsuario|EmbarcacoesFavoritasUsuarios', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('embarcacoes_id_embarcacao, usuarios_id', 'required'),
			array('embarcacoes_id_embarcacao, usuarios_id', 'numerical', 'integerOnly'=>true),
			array('id, embarcacoes_id_embarcacao, usuarios_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoesIdEmbarcacao' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id_embarcacao'),
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id_embarcacao' => null,
			'usuarios_id' => null,
			'embarcacoesIdEmbarcacao' => null,
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id_embarcacao', $this->embarcacoes_id_embarcacao);
		$criteria->compare('usuarios_id', $this->usuarios_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}