<?php

/**
 * This is the model base class for the table "classificados_views_modelos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClassificadosViewsModelos".
 *
 * Columns in table "classificados_views_modelos" available as properties of the model,
 * followed by relations of table "classificados_views_modelos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property string $data
 *
 * @property Embarcacoes $embarcacoes
 */
abstract class BaseClassificadosViewsModelos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'classificados_views_modelos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClassificadosViewsModelos|ClassificadosViewsModeloses', $n);
	}

	public static function representingColumn() {
		return 'data';
	}

	public function rules() {
		return array(
			array('data', 'required'),
			array('embarcacoes_id', 'numerical', 'integerOnly'=>true),
			array('embarcacoes_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'data' => Yii::t('app', 'Data'),
			'embarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}