<?php

/**
 * This is the model base class for the table "contatos_motor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ContatosMotor".
 *
 * Columns in table "contatos_motor" available as properties of the model,
 * followed by relations of table "contatos_motor" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_motor_anuncio
 * @property string $mensagem
 * @property string $email_rem
 * @property string $email_dest
 * @property string $nome
 * @property string $telefone
 * @property integer $status
 * @property string $data
 *
 * @property MotorAnuncio $idMotorAnuncio
 */
abstract class BaseContatosMotor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contatos_motor';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ContatosMotor|ContatosMotors', $n);
	}

	public static function representingColumn() {
		return 'mensagem';
	}

	public function rules() {
		return array(
			array('id_motor_anuncio, status', 'numerical', 'integerOnly'=>true),
			array('email_rem, email_dest, nome, telefone', 'length', 'max'=>80),
			array('mensagem, data', 'safe'),
			array('id_motor_anuncio, mensagem, email_rem, email_dest, nome, telefone, status, data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_motor_anuncio, mensagem, email_rem, email_dest, nome, telefone, status, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idMotorAnuncio' => array(self::BELONGS_TO, 'MotorAnuncio', 'id_motor_anuncio'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_motor_anuncio' => null,
			'mensagem' => Yii::t('app', 'Mensagem'),
			'email_rem' => Yii::t('app', 'Email Rem'),
			'email_dest' => Yii::t('app', 'Email Dest'),
			'nome' => Yii::t('app', 'Nome'),
			'telefone' => Yii::t('app', 'Telefone'),
			'status' => Yii::t('app', 'Status'),
			'data' => Yii::t('app', 'Data'),
			'idMotorAnuncio' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_motor_anuncio', $this->id_motor_anuncio);
		$criteria->compare('mensagem', $this->mensagem, true);
		$criteria->compare('email_rem', $this->email_rem, true);
		$criteria->compare('email_dest', $this->email_dest, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}