<?php

/**
 * This is the model base class for the table "avisos_minha_conta".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AvisosMinhaConta".
 *
 * Columns in table "avisos_minha_conta" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $embarcacao_fabricantes_id
 * @property integer $embarcacao_modelos_id
 * @property integer $usuarios_id
 * @property string $dataregistro
 * @property integer $embarcacao_macros_id
 *
 */
abstract class BaseAvisosMinhaConta extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'avisos_minha_conta';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AvisosMinhaConta|AvisosMinhaContas', $n);
	}

	public static function representingColumn() {
		return 'dataregistro';
	}

	public function rules() {
		return array(
			array('embarcacao_fabricantes_id, embarcacao_modelos_id, usuarios_id, embarcacao_macros_id', 'numerical', 'integerOnly'=>true),
			array('dataregistro', 'safe'),
			array('embarcacao_fabricantes_id, embarcacao_modelos_id, usuarios_id, dataregistro, embarcacao_macros_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacao_fabricantes_id, embarcacao_modelos_id, usuarios_id, dataregistro, embarcacao_macros_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacao_fabricantes_id' => Yii::t('app', 'Embarcacao Fabricantes'),
			'embarcacao_modelos_id' => Yii::t('app', 'Embarcacao Modelos'),
			'usuarios_id' => Yii::t('app', 'Usuarios'),
			'dataregistro' => Yii::t('app', 'Dataregistro'),
			'embarcacao_macros_id' => Yii::t('app', 'Embarcacao Macros'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacao_fabricantes_id', $this->embarcacao_fabricantes_id);
		$criteria->compare('embarcacao_modelos_id', $this->embarcacao_modelos_id);
		$criteria->compare('usuarios_id', $this->usuarios_id);
		$criteria->compare('dataregistro', $this->dataregistro, true);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}