<?php

/**
 * This is the model base class for the table "banners_clicks".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BannersClicks".
 *
 * Columns in table "banners_clicks" available as properties of the model,
 * followed by relations of table "banners_clicks" available as properties of the model.
 *
 * @property integer $id
 * @property string $data
 * @property string $ip
 * @property integer $usuarios_id
 * @property integer $banners_id
 *
 * @property Banners $banners
 * @property Usuarios $usuarios
 */
abstract class BaseBannersClicks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banners_clicks';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BannersClicks|BannersClicks', $n);
	}

	public static function representingColumn() {
		return 'data';
	}

	public function rules() {
		return array(
			array('banners_id', 'required'),
			array('usuarios_id, banners_id', 'numerical', 'integerOnly'=>true),
			array('ip', 'length', 'max'=>30),
			array('id, data, ip, usuarios_id, banners_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'banners' => array(self::BELONGS_TO, 'Banners', 'banners_id'),
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'data' => Yii::t('app', 'Data'),
			'ip' => Yii::t('app', 'Ip'),
			'usuarios_id' => null,
			'banners_id' => null,
			'banners' => null,
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('ip', $this->ip, true);
		$criteria->compare('usuarios_id', $this->usuarios_id);
		$criteria->compare('banners_id', $this->banners_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}