<?php

/**
 * This is the model base class for the table "embarcacao_imagens".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacaoImagens".
 *
 * Columns in table "embarcacao_imagens" available as properties of the model,
 * followed by relations of table "embarcacao_imagens" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property string $imagem
 * @property integer $turbo
 * @property integer $principal
 * @property integer $status
 *
 * @property Embarcacoes $embarcacoes
 */
abstract class BaseEmbarcacaoImagens extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacao_imagens';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacaoImagens|EmbarcacaoImagens', $n);
	}

	public static function representingColumn() {
		return 'imagem';
	}

	public function rules() {
		return array(
			array('embarcacoes_id, imagem', 'required'),
			array('embarcacoes_id, turbo, principal, status', 'numerical', 'integerOnly'=>true),
			array('imagem', 'length', 'max'=>200),
			array('turbo, principal, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, imagem, turbo, principal, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'imagem' => Yii::t('app', 'Imagem'),
			'turbo' => Yii::t('app', 'Turbo'),
			'principal' => Yii::t('app', 'Principal'),
			'status' => Yii::t('app', 'Status'),
			'embarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('turbo', $this->turbo);
		$criteria->compare('principal', $this->principal);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}