<?php

/**
 * This is the model base class for the table "usuario_classificacoes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsuarioClassificacoes".
 *
 * Columns in table "usuario_classificacoes" available as properties of the model,
 * followed by relations of table "usuario_classificacoes" available as properties of the model.
 *
 * @property integer $id
 * @property string $titulo
 * @property string $alias
 * @property integer $status
 *
 * @property Usuarios[] $usuarioses
 */
abstract class BaseUsuarioClassificacoes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuario_classificacoes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsuarioClassificacoes|UsuarioClassificacoes', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo, alias', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('titulo, alias', 'length', 'max'=>45),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, titulo, alias, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarioses' => array(self::HAS_MANY, 'Usuarios', 'usuario_classificacoes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'alias' => Yii::t('app', 'Alias'),
			'status' => Yii::t('app', 'Status'),
			'usuarioses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}