<?php

/**
 * This is the model base class for the table "redirects".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Redirects".
 *
 * Columns in table "redirects" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $de
 * @property string $para
 * @property integer $status
 *
 */
abstract class BaseRedirects extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'redirects';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Redirects|Redirects', $n);
	}

	public static function representingColumn() {
		return 'de';
	}

	public function rules() {
		return array(
			array('de, para', 'required'),
			array('status', 'numerical', 'integerOnly'=>true),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, de, para, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'de' => Yii::t('app', 'De'),
			'para' => Yii::t('app', 'Para'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('de', $this->de, true);
		$criteria->compare('para', $this->para, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}