<?php

/**
 * This is the model base class for the table "vendas_bombarco".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VendasBombarco".
 *
 * Columns in table "vendas_bombarco" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property integer $venda_pelo_bombarco
 * @property string $data
 *
 */
abstract class BaseVendasBombarco extends GxActiveRecord {

	public $proprietario;
	public $email;
	public $valor;
	public $data_de;
	public $data_ate;
	public $pelobb;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'vendas_bombarco';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VendasBombarco|VendasBombarcos', $n);
	}

	public static function representingColumn() {
		return 'data';
	}

	public function rules() {
		return array(
			array('embarcacoes_id, venda_pelo_bombarco', 'numerical', 'integerOnly'=>true),
			array('data', 'safe'),
			array('embarcacoes_id, venda_pelo_bombarco, data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, venda_pelo_bombarco, data, email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => Yii::t('app', 'Embarcacoes'),
			'venda_pelo_bombarco' => Yii::t('app', 'Venda Pelo Bombarco'),
			'data' => Yii::t('app', 'Data'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->with = array('embarcacoes');

		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		

		if($this->data_de != "" && $this->data_ate != "" && $this->venda_pelo_bombarco != "") {
			$criteria->condition = "data >= '".$this->data_de."' and data <= '".$this->data_ate."' and venda_pelo_bombarco = ".$this->venda_pelo_bombarco;	
		}
		else if($this->data_de != "" && $this->data_ate != "" && $this->venda_pelo_bombarco == "") {
			$criteria->condition = "data >= '".$this->data_de."' and data <= '".$this->data_ate."'";	
			$criteria->compare('venda_pelo_bombarco', $this->venda_pelo_bombarco);
		}
		else {
			$criteria->compare('data', $this->data, true);	
			$criteria->compare('venda_pelo_bombarco', $this->venda_pelo_bombarco);
		}

		$criteria->compare('email', $this->email);
		$criteria->compare('valor', $this->valor);
		$criteria->compare('proprietario', $this->proprietario);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}