<?php

/**
 * This is the model base class for the table "acessorio_tipos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AcessorioTipos".
 *
 * Columns in table "acessorio_tipos" available as properties of the model,
 * followed by relations of table "acessorio_tipos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacao_macros_id
 * @property string $titulo
 * @property integer $status
 *
 * @property AcessorioModelos[] $acessorioModeloses
 * @property EmbarcacaoMacros $embarcacaoMacros
 */
abstract class BaseAcessorioTipos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'acessorio_tipos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AcessorioTipos|AcessorioTiposes', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('embarcacao_macros_id, titulo', 'required'),
			array('embarcacao_macros_id, status', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>45),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacao_macros_id, titulo, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'acessorioModeloses' => array(self::HAS_MANY, 'AcessorioModelos', 'acessorio_tipos_id'),
			'embarcacaoMacros' => array(self::BELONGS_TO, 'EmbarcacaoMacros', 'embarcacao_macros_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacao_macros_id' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'status' => Yii::t('app', 'Status'),
			'acessorioModeloses' => null,
			'embarcacaoMacros' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}