<?php

/**
 * This is the model base class for the table "embarcacoes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Embarcacoes".
 *
 * Columns in table "embarcacoes" available as properties of the model,
 * followed by relations of table "embarcacoes" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacao_macros_id
 * @property integer $embarcacao_modelos_id
 * @property string $titulo
 * @property string $slug
 * @property integer $ano
 * @property integer $estados_id
 * @property integer $cidades_id
 * @property string $valor
 * @property string $estado
 * @property integer $qntmotores
 * @property string $descricao
 * @property string $views
 * @property string $video
 * @property integer $destaque
 * @property integer $plano_usuarios_id
 * @property integer $status
 * @property string $email
 * @property integer $macros_id
 *
 * @property Contatos[] $contatoses
 * @property Conteudos[] $conteudoses
 * @property EmbarcacaoAcessorios[] $embarcacaoAcessorioses
 * @property EmbarcacaoImagens[] $embarcacaoImagens
 * @property EmbarcacaoImpressoes[] $embarcacaoImpressoes
 * @property EmbarcacaoItensAdicionais[] $embarcacaoItensAdicionaises
 * @property EmbarcacaoMetricas[] $embarcacaoMetricases
 * @property EmbarcacaoSeo[] $embarcacaoSeos
 * @property Macros $macros
 * @property Cidades $cidades
 * @property EmbarcacaoMacros $embarcacaoMacros
 * @property EmbarcacaoModelos $embarcacaoModelos
 * @property Estados $estados
 * @property PlanoUsuarios $planoUsuarios
 * @property EmbarcacoesFavoritasUsuario[] $embarcacoesFavoritasUsuarios
 * @property EmbarcacoesHasEmbarcacaoRecursosAdicionais[] $embarcacoesHasEmbarcacaoRecursosAdicionaises
 * @property Motores[] $motores
 * @property UsuariosEmbarcacoes[] $usuariosEmbarcacoes
 */
abstract class BaseEmbarcacoes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacoes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Embarcacoes|Embarcacoes', $n);
	}

	public static function representingColumn() {
		return 'estado';
	}
	public function rules() {
		return array(
            array('macros_id, embarcacao_macros_id, embarcacao_modelos_id, estado', 'required'),
            array('macros_id, embarcacao_macros_id, embarcacao_modelos_id, plano_usuarios_id, ano, estados_id, cidades_id, qntmotores, destaque, editado, destaque_zeromilhas, status', 'numerical', 'integerOnly'=>true),
            array('titulo, email', 'length', 'max'=>100),
            array('slug', 'length', 'max'=>125),
            array('combustivel', 'length', 'max'=>125),
            array('imagemprincipal', 'length', 'max'=>200),
            array('valor', 'length', 'max'=>10),
            array('estado', 'length', 'max'=>1),
            array('views', 'length', 'max'=>20),
            array('descricao, video, data_ativacao, destaque_zeromilhas', 'safe'),
            array('plano_usuarios_id, data_ativacao, imagemprincipal, titulo, slug, email, ano, estados_id, cidades_id, valor, combustivel, qntmotores, descricao, views, video, destaque, editado, status, destaque_zeromilhas', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, macros_id, embarcacao_macros_id, data_ativacao, imagemprincipal, embarcacao_modelos_id, plano_usuarios_id, titulo, slug, email, ano, estados_id, cidades_id, valor, combustivel, estado, qntmotores, descricao, views, video, destaque, editado, status, destaque_zeromilhas', 'safe', 'on'=>'search'),
        );		
	}

	public function relations() {
		return array(			
			'conteudoses' => array(self::HAS_MANY, 'Conteudos', 'embarcacoes_id'),
			'embarcacaoAcessorioses' => array(self::HAS_MANY, 'EmbarcacaoAcessorios', 'embarcacoes_id'),
			'embarcacaoImagens' => array(self::HAS_MANY, 'EmbarcacaoImagens', 'embarcacoes_id'),
			'embarcacaoImpressoes' => array(self::HAS_MANY, 'EmbarcacaoImpressoes', 'embarcacoes_id'),
			'embarcacaoItensAdicionaises' => array(self::HAS_MANY, 'EmbarcacaoItensAdicionais', 'embarcacoes_id'),
			'embarcacaoMetricases' => array(self::HAS_MANY, 'EmbarcacaoMetricas', 'embarcacoes_id'),
			'macros' => array(self::BELONGS_TO, 'Macros', 'macros_id'),
			'cidades' => array(self::BELONGS_TO, 'Cidades', 'cidades_id'),
			'embarcacaoMacros' => array(self::BELONGS_TO, 'EmbarcacaoMacros', 'embarcacao_macros_id'),
			'embarcacaoModelos' => array(self::BELONGS_TO, 'EmbarcacaoModelos', 'embarcacao_modelos_id'),
			//'embarcacaoFabricantes' => array(self::BELONGS_TO,'EmbarcacaoFabricantes', array('embarcacao_fabricantes_id'=> 'id'),'through'=>'embarcacaoModelos'),

			'embarcacaoFabricantes' => array(self::BELONGS_TO, 'EmbarcacaoFabricantes', 'embarcacao_fabricantes_id'),
			
			'estados' => array(self::BELONGS_TO, 'Estados', 'estados_id'),
			'contatoses' => array(self::HAS_MANY, 'Contatos', 'embarcacoes_id'),
			'planoUsuarios' => array(self::BELONGS_TO, 'PlanoUsuarios', 'plano_usuarios_id'),
			'embarcacoesFavoritasUsuarios' => array(self::HAS_MANY, 'EmbarcacoesFavoritasUsuario', 'embarcacoes_id_embarcacao'),
			'embarcacaoRecursosAdicionaises' => array(self::MANY_MANY, 'EmbarcacaoRecursosAdicionais', 'embarcacoes_has_embarcacao_recursos_adicionais(embarcacoes_id, embarcacao_recursos_adicionais_id)'),
			'motores' => array(self::HAS_MANY, 'Motores', 'embarcacoes_id'),
			'usuariosEmbarcacoes' => array(self::HAS_MANY, 'UsuariosEmbarcacoes', 'embarcacoes_id'),
			'tags' => array(self::MANY_MANY, 'Tags', 'embarcacoes_has_tags(embarcacoes_id, tags_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'usuarioses' => 'EmbarcacoesFavoritasUsuario',
			'embarcacaoRecursosAdicionaises' => 'EmbarcacoesHasEmbarcacaoRecursosAdicionais',
			'tags' => 'EmbarcacoesHasTags',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacao_macros_id' => null,
			'embarcacao_modelos_id' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'slug' => Yii::t('app', 'Slug'),
			'ano' => Yii::t('app', 'Ano'),
			'estados_id' => null,
			'cidades_id' => null,
			
			'data_ativacao'=> 'Data de ativação',
			'valor' => Yii::t('app', 'Valor'),
			'editado' => Yii::t('app', 'Editado'),
			'estado' => Yii::t('app', 'Estado'),
			'qntmotores' => Yii::t('app', 'Qntmotores'),
			'descricao' => Yii::t('app', 'Descricao'),
			'views' => Yii::t('app', 'Views'),
			'video' => Yii::t('app', 'Video'),
			'destaque' => Yii::t('app', 'Destaque'),
			'plano_usuarios_id' => null,
			'status' => Yii::t('app', 'Status'),
			'email' => Yii::t('app', 'Email'),
			'macros_id' => null,
			'contatoses' => null,
			'embarcacaoFabricantes' => 'Fabricante',
			'imagemprincipal'=>'Imagem Principal',
			'conteudoses' => null,
			'macros_id' => null,
			'contatoses' => null,
			'embarcacaoAcessorioses' => null,
			'embarcacaoImagens' => null,
			'embarcacaoImpressoes' => null,
			'embarcacaoItensAdicionaises' => null,
			'embarcacaoMetricases' => null,
			'embarcacaoSeos' => null,
			'macros' => null,
			'cidades' => null,
			'embarcacaoMacros' => null,
			'embarcacaoModelos' => null,
			'estados' => null,
			'planoUsuarios' => null,
			'embarcacoesFavoritasUsuarios' => null,
			'usuarioses' => null,
			'embarcacaoRecursosAdicionaises' => null,
			'motores' => null,
			'tags' => null,
			'usuariosEmbarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);
		$criteria->compare('embarcacao_modelos_id', $this->embarcacao_modelos_id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('ano', $this->ano);
		$criteria->compare('estados_id', $this->estados_id);
		$criteria->compare('cidades_id', $this->cidades_id);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('estado', $this->estado, true);
		$criteria->compare('qntmotores', $this->qntmotores);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('views', $this->views, true);
		$criteria->compare('video', $this->video, true);
		$criteria->compare('destaque', $this->destaque);
		$criteria->compare('plano_usuarios_id', $this->plano_usuarios_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('macros_id', $this->macros_id);
		$criteria->compare('editado', $this->editado);
		$criteria->compare('embarcacao_fabricantes_id', $this->embarcacao_fabricantes_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}