<?php

/**
 * This is the model base class for the table "usuarios".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuarios".
 *
 * Columns in table "usuarios" available as properties of the model,
 * followed by relations of table "usuarios" available as properties of the model.
 *
 * @property integer $id
 * @property integer $usuario_classificacoes_id
 * @property string $pessoa
 * @property string $nome
 * @property string $sobrenome
 * @property string $email
 * @property string $senha
 * @property string $data_nascimento
 * @property string $cpf
 * @property string $telefone
 * @property string $celular
 * @property integer $estados_id
 * @property integer $cidades_id
 * @property string $googleplus
 * @property string $facebook
 * @property string $dataregistro
 * @property string $razaosocial
 * @property string $nomefantasia
 * @property string $cnpj
 * @property string $nextel
 * @property string $cep
 * @property string $endereco
 * @property string $numero
 * @property string $bairro
 * @property string $complemento
 *
 * @property Banners[] $banners
 * @property Comparador[] $comparadors
 * @property Contatos[] $contatoses
 * @property Conteudos[] $conteudoses
 * @property EmbarcacoesFavoritasUsuario[] $embarcacoesFavoritasUsuarios
 * @property Empresas[] $empresases
 * @property LogLogins[] $logLogins
 * @property Ordens[] $ordens
 * @property PlanoUsuarios[] $planoUsuarioses
 * @property Transacoes[] $transacoes
 * @property UsuarioPerguntas[] $usuarioPerguntases
 * @property Cidades $cidades
 * @property Estados $estados
 * @property UsuarioClassificacoes $usuarioClassificacoes
 * @property UsuariosEmbarcacoes[] $usuariosEmbarcacoes
 * @property UsuariosRecuperacaoSenha[] $usuariosRecuperacaoSenhas
 */
abstract class BaseUsuarios extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuarios';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuarios|Usuarioses', $n);
	}

	public static function representingColumn() {
		return 'pessoa';
	}

	public function rules() {
		return array(
			array('usuario_classificacoes_id, pessoa, email, senha,telefone,celular', 'required'),
			array('usuario_classificacoes_id, estados_id, cidades_id', 'numerical', 'integerOnly'=>true),
			array('pessoa', 'length', 'max'=>1),
			array('nome, sobrenome, email, senha, cnpj', 'length', 'max'=>100),
			array('cpf, googleplus, facebook, cep, complemento', 'length', 'max'=>45),
			array('telefone, celular,telefone2,celular2', 'length', 'max'=>25),
			array('razaosocial, nomefantasia, endereco, bairro', 'length', 'max'=>150),
			array('nextel', 'length', 'max'=>50),
			array('numero', 'length', 'max'=>20),
			array('data_nascimento, dataregistro', 'safe'),
			array('nome, sobrenome, data_nascimento, cpf, telefone, celular, estados_id, cidades_id, googleplus, facebook, dataregistro, razaosocial, nomefantasia, cnpj, nextel, cep, endereco, numero, bairro, complemento', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, usuario_classificacoes_id, pessoa, nome, sobrenome, email, senha, data_nascimento, cpf, telefone, celular, estados_id, cidades_id, googleplus, facebook, dataregistro, razaosocial, nomefantasia, cnpj, nextel, cep, endereco, numero, bairro, complemento', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'banners' => array(self::HAS_MANY, 'Banners', 'usuarios_id'),
			'comparadors' => array(self::HAS_MANY, 'Comparador', 'usuarios_id'),
			'contatoses' => array(self::HAS_MANY, 'Contatos', 'usuarios_id'),
			'conteudoses' => array(self::HAS_MANY, 'Conteudos', 'usuarios_id'),
			'embarcacoesFavoritasUsuarios' => array(self::HAS_MANY, 'EmbarcacoesFavoritasUsuario', 'usuarios_id'),
			'empresases' => array(self::HAS_MANY, 'Empresas', 'usuarios_id'),
			'logLogins' => array(self::HAS_MANY, 'LogLogins', 'usuarios_id'),
			'ordens' => array(self::HAS_MANY, 'Ordens', 'usuarios_id'),
			'planoUsuarioses' => array(self::HAS_MANY, 'PlanoUsuarios', 'usuarios_id'),
			'transacoes' => array(self::HAS_MANY, 'Transacoes', 'usuarios_id'),
			'usuarioPerguntases' => array(self::HAS_MANY, 'UsuarioPerguntas', 'usuarios_id'),
			'cidades' => array(self::BELONGS_TO, 'Cidades', 'cidades_id'),
			'estados' => array(self::BELONGS_TO, 'Estados', 'estados_id'),
			'usuarioClassificacoes' => array(self::BELONGS_TO, 'UsuarioClassificacoes', 'usuario_classificacoes_id'),
			'usuariosEmbarcacoes' => array(self::HAS_MANY, 'UsuariosEmbarcacoes', 'usuarios_id'),
			'usuariosRecuperacaoSenhas' => array(self::HAS_MANY, 'UsuariosRecuperacaoSenha', 'usuarios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'usuario_classificacoes_id' => null,
			'pessoa' => Yii::t('app', 'Pessoa'),
			'nome' => Yii::t('app', 'Nome'),
			'sobrenome' => Yii::t('app', 'Sobrenome'),
			'email' => Yii::t('app', 'Email'),
			'senha' => Yii::t('app', 'Senha'),
			'data_nascimento' => Yii::t('app', 'Data Nascimento'),
			'cpf' => Yii::t('app', 'Cpf'),
			'telefone' => Yii::t('app', 'Telefone'),
			'celular' => Yii::t('app', 'Celular'),
                    	'telefone2' => Yii::t('app', 'Telefone'),
			'celular2' => Yii::t('app', 'Celular'),
			'estados_id' => null,
			'cidades_id' => null,
			'googleplus' => Yii::t('app', 'Googleplus'),
			'facebook' => Yii::t('app', 'Facebook'),
			'dataregistro' => Yii::t('app', 'Dataregistro'),
			'razaosocial' => Yii::t('app', 'Razaosocial'),
			'nomefantasia' => Yii::t('app', 'Nomefantasia'),
			'cnpj' => Yii::t('app', 'Cnpj'),
			'nextel' => Yii::t('app', 'Nextel'),
			'cep' => Yii::t('app', 'Cep'),
			'endereco' => Yii::t('app', 'Endereco'),
			'numero' => Yii::t('app', 'Numero'),
			'bairro' => Yii::t('app', 'Bairro'),
			'complemento' => Yii::t('app', 'Complemento'),
			'banners' => null,
			'comparadors' => null,
			'contatoses' => null,
			'conteudoses' => null,
			'embarcacoesFavoritasUsuarios' => null,
			'empresases' => null,
			'logLogins' => null,
			'ordens' => null,
			'planoUsuarioses' => null,
			'transacoes' => null,
			'usuarioPerguntases' => null,
			'cidades' => null,
			'estados' => null,
			'usuarioClassificacoes' => null,
			'usuariosEmbarcacoes' => null,
			'usuariosRecuperacaoSenhas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('usuario_classificacoes_id', $this->usuario_classificacoes_id);
		$criteria->compare('pessoa', $this->pessoa, true);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('sobrenome', $this->sobrenome, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('senha', $this->senha, true);
		$criteria->compare('data_nascimento', $this->data_nascimento, true);
		$criteria->compare('cpf', $this->cpf, true);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('celular', $this->celular, true);		
                $criteria->compare('telefone2', $this->telefone2, true);
		$criteria->compare('celular2', $this->celular2, true);
		$criteria->compare('estados_id', $this->estados_id);
		$criteria->compare('cidades_id', $this->cidades_id);
		$criteria->compare('googleplus', $this->googleplus, true);
		$criteria->compare('facebook', $this->facebook, true);
		$criteria->compare('dataregistro', $this->dataregistro, true);
		$criteria->compare('razaosocial', $this->razaosocial, true);
		$criteria->compare('nomefantasia', $this->nomefantasia, true);
		$criteria->compare('cnpj', $this->cnpj, true);
		$criteria->compare('nextel', $this->nextel, true);
		$criteria->compare('cep', $this->cep, true);
		$criteria->compare('endereco', $this->endereco, true);
		$criteria->compare('numero', $this->numero, true);
		$criteria->compare('bairro', $this->bairro, true);
		$criteria->compare('complemento', $this->complemento, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}