<?php

/**
 * This is the model base class for the table "banners".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Banners".
 *
 * Columns in table "banners" available as properties of the model,
 * followed by relations of table "banners" available as properties of the model.
 *
 * @property integer $id
 * @property string $titulo
 * @property integer $embarcacao_macros_id
 * @property integer $usuarios_id
 * @property string $imagem
 * @property string $imagem_topo
 * @property integer $local
 * @property string $views
 * @property string $cliques
 * @property string $inicio
 * @property string $fim
 * @property string $link
 * @property integer $status
 *
 * @property Usuarios $usuarios
 * @property EmbarcacaoMacros $embarcacaoMacros
 */
abstract class BaseBanners extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'banners';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Banners|Banners', $n);
	}

	public static function representingColumn() {
		return 'imagem';
	}

	public function rules() {
		return array(
			array('imagem, local', 'required'),
			array('embarcacao_macros_id, usuarios_id, local, status', 'numerical', 'integerOnly'=>true),
			array('titulo, imagem, imagem_topo', 'length', 'max'=>100),
			array('views, cliques', 'length', 'max'=>20),
			array('link', 'length', 'max'=>500),
			array('inicio, fim', 'safe'),
			array('titulo, embarcacao_macros_id, usuarios_id, imagem_topo, views, cliques, inicio, fim, link, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, titulo, embarcacao_macros_id, usuarios_id, imagem, imagem_topo, local, views, cliques, inicio, fim, link, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
			'embarcacaoMacros' => array(self::BELONGS_TO, 'EmbarcacaoMacros', 'embarcacao_macros_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'embarcacao_macros_id' => null,
			'usuarios_id' => null,
			'imagem' => Yii::t('app', 'Imagem'),
			'imagem_topo' => Yii::t('app', 'Imagem Topo'),
			'local' => Yii::t('app', 'Local'),
			'views' => Yii::t('app', 'Views'),
			'cliques' => Yii::t('app', 'Cliques'),
			'inicio' => Yii::t('app', 'Inicio'),
			'fim' => Yii::t('app', 'Fim'),
			'link' => Yii::t('app', 'Link'),
			'status' => Yii::t('app', 'Status'),
			'usuarios' => null,
			'embarcacaoMacros' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);
		$criteria->compare('usuarios_id', $this->usuarios_id);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('imagem_topo', $this->imagem_topo, true);
		$criteria->compare('local', $this->local);
		$criteria->compare('views', $this->views, true);
		$criteria->compare('cliques', $this->cliques, true);
		$criteria->compare('inicio', $this->inicio, true);
		$criteria->compare('fim', $this->fim, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}