<?php

/**
 * This is the model base class for the table "bairros".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bairros".
 *
 * Columns in table "bairros" available as properties of the model,
 * followed by relations of table "bairros" available as properties of the model.
 *
 * @property integer $id
 * @property string $nome
 * @property integer $cidades_id
 *
 * @property Cidades $cidades
 */
abstract class BaseBairros extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bairros';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bairros|Bairroses', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome, cidades_id', 'required'),
			array('cidades_id', 'numerical', 'integerOnly'=>true),
			array('nome', 'length', 'max'=>100),
			array('id, nome, cidades_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cidades' => array(self::BELONGS_TO, 'Cidades', 'cidades_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nome' => Yii::t('app', 'Nome'),
			'cidades_id' => null,
			'cidades' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('cidades_id', $this->cidades_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}