<?php

/**
 * This is the model base class for the table "motores".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Motores".
 *
 * Columns in table "motores" available as properties of the model,
 * followed by relations of table "motores" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property integer $motor_modelos_id
 * @property string $titulo
 * @property string $horas
 * @property integer $status
 * @property integer $motor_fabricantes_id
 *
 * @property Embarcacoes $embarcacoes
 * @property MotorModelos $motorModelos
 * @property MotorFabricantes $motorFabricantes
 */
abstract class BaseMotores extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'motores';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Motores|Motores', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('embarcacoes_id, titulo', 'required'),
			array('embarcacoes_id, motor_modelos_id, status, motor_fabricantes_id', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>45),
			array('horas', 'safe'),
			array('motor_modelos_id, horas, status, motor_fabricantes_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, motor_modelos_id, titulo, horas, status, motor_fabricantes_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
			'motorModelos' => array(self::BELONGS_TO, 'MotorModelos', 'motor_modelos_id'),
			'motorFabricantes' => array(self::BELONGS_TO, 'MotorFabricantes', 'motor_fabricantes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'motor_modelos_id' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'horas' => Yii::t('app', 'Horas'),
			'status' => Yii::t('app', 'Status'),
			'motor_fabricantes_id' => null,
			'embarcacoes' => null,
			'motorModelos' => null,
			'motorFabricantes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('motor_modelos_id', $this->motor_modelos_id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('horas', $this->horas, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('motor_fabricantes_id', $this->motor_fabricantes_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}