<?php

/**
 * This is the model base class for the table "usuarios_recuperacao_senha".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsuariosRecuperacaoSenha".
 *
 * Columns in table "usuarios_recuperacao_senha" available as properties of the model,
 * followed by relations of table "usuarios_recuperacao_senha" available as properties of the model.
 *
 * @property integer $id
 * @property string $token
 * @property integer $usuarios_id
 *
 * @property Usuarios $usuarios
 */
abstract class BaseUsuariosRecuperacaoSenha extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usuarios_recuperacao_senha';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsuariosRecuperacaoSenha|UsuariosRecuperacaoSenhas', $n);
	}

	public static function representingColumn() {
		return 'token';
	}

	public function rules() {
		return array(
			array('token, usuarios_id', 'required'),
			array('usuarios_id', 'numerical', 'integerOnly'=>true),
			array('token', 'length', 'max'=>200),
			array('id, token, usuarios_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'token' => Yii::t('app', 'Token'),
			'usuarios_id' => null,
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('token', $this->token, true);
		$criteria->compare('usuarios_id', $this->usuarios_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}