<?php

/**
 * This is the model base class for the table "logs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Logs".
 *
 * Columns in table "logs" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $id_item
 * @property string $chave
 * @property string $valor
 * @property string $data
 *
 */
abstract class BaseLogs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'logs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Logs|Logs', $n);
	}

	public static function representingColumn() {
		return 'chave';
	}

	public function rules() {
		return array(
			array('chave, valor, data', 'required'),
			array('id_item', 'length', 'max'=>20),
			array('chave', 'length', 'max'=>45),
			array('id_item', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_item, chave, valor, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_item' => Yii::t('app', 'Id Item'),
			'chave' => Yii::t('app', 'Chave'),
			'valor' => Yii::t('app', 'Valor'),
			'data' => Yii::t('app', 'Data'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('id_item', $this->id_item, true);
		$criteria->compare('chave', $this->chave, true);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}