<?php

/**
 * This is the model base class for the table "correios".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Correios".
 *
 * Columns in table "correios" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $uf
 * @property string $cidade
 * @property string $bairro
 *
 */
abstract class BaseCorreios extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'correios';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Correios|Correioses', $n);
	}

	public static function representingColumn() {
		return 'uf';
	}

	public function rules() {
		return array(
			array('uf, cidade, bairro', 'required'),
			array('uf', 'length', 'max'=>2),
			array('id, uf, cidade, bairro', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'uf' => Yii::t('app', 'Uf'),
			'cidade' => Yii::t('app', 'Cidade'),
			'bairro' => Yii::t('app', 'Bairro'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('uf', $this->uf, true);
		$criteria->compare('cidade', $this->cidade, true);
		$criteria->compare('bairro', $this->bairro, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}