<?php

/**
 * This is the model base class for the table "embarcacao_impressoes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacaoImpressoes".
 *
 * Columns in table "embarcacao_impressoes" available as properties of the model,
 * followed by relations of table "embarcacao_impressoes" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacoes_id
 * @property string $views
 * @property string $clicks
 * @property string $limitviews
 * @property string $limitdate
 * @property integer $status
 *
 * @property Embarcacoes $embarcacoes
 */
abstract class BaseEmbarcacaoImpressoes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacao_impressoes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacaoImpressoes|EmbarcacaoImpressoes', $n);
	}

	public static function representingColumn() {
		return 'limitdate';
	}

	public function rules() {
		return array(
			array('embarcacoes_id', 'required'),
			array('embarcacoes_id, status', 'numerical', 'integerOnly'=>true),
			array('views, clicks, limitviews', 'length', 'max'=>20),
			array('views, clicks, limitviews, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacoes_id, views, clicks, limitviews, limitdate, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacoes_id' => null,
			'views' => Yii::t('app', 'Views'),
			'clicks' => Yii::t('app', 'Clicks'),
			'limitviews' => Yii::t('app', 'Limitviews'),
			'limitdate' => Yii::t('app', 'Limitdate'),
			'status' => Yii::t('app', 'Status'),
			'embarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);
		$criteria->compare('views', $this->views, true);
		$criteria->compare('clicks', $this->clicks, true);
		$criteria->compare('limitviews', $this->limitviews, true);
		$criteria->compare('limitdate', $this->limitdate, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}