<?php

/**
 * This is the model base class for the table "transacao_embarcacoes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TransacaoEmbarcacoes".
 *
 * Columns in table "transacao_embarcacoes" available as properties of the model,
 * followed by relations of table "transacao_embarcacoes" available as properties of the model.
 *
 * @property integer $id
 * @property string $tid
 * @property string $valor
 * @property integer $status
 * @property integer $usuarios_id
 * @property integer $embarcacoes_id
 *
 * @property Usuarios $usuarios
 * @property Embarcacoes $embarcacoes
 */
abstract class BaseTransacaoEmbarcacoes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'transacao_embarcacoes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TransacaoEmbarcacoes|TransacaoEmbarcacoes', $n);
	}

	public static function representingColumn() {
		return 'tid';
	}

	public function rules() {
		return array(
			array('tid, valor, usuarios_id, embarcacoes_id', 'required'),
			array('status, usuarios_id, embarcacoes_id', 'numerical', 'integerOnly'=>true),
			array('tid', 'length', 'max'=>45),
			array('valor', 'length', 'max'=>10),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tid, valor, status, usuarios_id, embarcacoes_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
			'embarcacoes' => array(self::BELONGS_TO, 'Embarcacoes', 'embarcacoes_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tid' => Yii::t('app', 'Tid'),
			'valor' => Yii::t('app', 'Valor'),
			'status' => Yii::t('app', 'Status'),
			'usuarios_id' => null,
			'embarcacoes_id' => null,
			'usuarios' => null,
			'embarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tid', $this->tid, true);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('usuarios_id', $this->usuarios_id);
		$criteria->compare('embarcacoes_id', $this->embarcacoes_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}