<?php

/**
 * This is the model base class for the table "zeromilhas_views_empresas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ZeromilhasViewsEmpresas".
 *
 * Columns in table "zeromilhas_views_empresas" available as properties of the model,
 * followed by relations of table "zeromilhas_views_empresas" available as properties of the model.
 *
 * @property integer $id
 * @property integer $id_empresa
 * @property string $data
 *
 * @property Empresas $idEmpresa
 */
abstract class BaseZeromilhasViewsEmpresas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'zeromilhas_views_empresas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ZeromilhasViewsEmpresas|ZeromilhasViewsEmpresases', $n);
	}

	public static function representingColumn() {
		return 'data';
	}

	public function rules() {
		return array(
			array('id_empresa', 'numerical', 'integerOnly'=>true),
			array('data', 'safe'),
			array('id_empresa, data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, id_empresa, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empresa' => array(self::BELONGS_TO, 'Empresas', 'id_empresa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'id_empresa' => null,
			'data' => Yii::t('app', 'Data'),
			'idEmpresa' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('id_empresa', $this->id_empresa);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}