<?php

/**
 * This is the model base class for the table "embarcacao_modelos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacaoModelos".
 *
 * Columns in table "embarcacao_modelos" available as properties of the model,
 * followed by relations of table "embarcacao_modelos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $embarcacao_macros_id
 * @property integer $embarcacao_fabricantes_id
 * @property integer $embarcacao_tipos_id
 * @property string $titulo
 * @property string $slug
 * @property string $tamanho
 * @property integer $passageiros
 * @property integer $acomodacoes
 * @property string $comprimento
 * @property string $boca
 * @property string $calado
 * @property string $pedireito
 * @property string $pesocasco
 * @property string $tanquecombustivel
 * @property string $tanqueagua
 * @property string $consumo
 * @property integer $ncamarotes
 * @property integer $nbanheiros
 * @property string $motor_de_fabrica
 * @property integer $status
 *
 * @property EmbarcacaoFabricantes $embarcacaoFabricantes
 * @property EmbarcacaoMacros $embarcacaoMacros
 * @property EmbarcacaoTipos $embarcacaoTipos
 * @property EmbarcacaoModelosEditavel[] $embarcacaoModelosEditavels
 * @property Embarcacoes[] $embarcacoes
 * @property EmbarcacoesSeo[] $embarcacoesSeos
 * @property TabelaEmbarcacoes[] $tabelaEmbarcacoes
 */
abstract class BaseEmbarcacaoModelos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacao_modelos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacaoModelos|EmbarcacaoModeloses', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('embarcacao_macros_id, embarcacao_fabricantes_id, embarcacao_tipos_id, titulo, slug', 'required'),
			array('embarcacao_macros_id, embarcacao_fabricantes_id, embarcacao_tipos_id, passageiros, acomodacoes, ncamarotes, nbanheiros, status', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>100),
			array('slug', 'length', 'max'=>125),
			array('tamanho', 'length', 'max'=>10),
			array('comprimento, boca, calado, pedireito, pesocasco, tanquecombustivel, tanqueagua, consumo', 'length', 'max'=>20),
			array('motor_de_fabrica', 'length', 'max'=>45),
			array('tamanho, passageiros, acomodacoes, comprimento, boca, calado, pedireito, pesocasco, tanquecombustivel, tanqueagua, consumo, ncamarotes, nbanheiros, motor_de_fabrica, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, embarcacao_macros_id, embarcacao_fabricantes_id, embarcacao_tipos_id, titulo, slug, tamanho, passageiros, acomodacoes, comprimento, boca, calado, pedireito, pesocasco, tanquecombustivel, tanqueagua, consumo, ncamarotes, nbanheiros, motor_de_fabrica, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacaoFabricantes' => array(self::BELONGS_TO, 'EmbarcacaoFabricantes', 'embarcacao_fabricantes_id'),
			'embarcacaoMacros' => array(self::BELONGS_TO, 'EmbarcacaoMacros', 'embarcacao_macros_id'),
			'embarcacaoTipos' => array(self::BELONGS_TO, 'EmbarcacaoTipos', 'embarcacao_tipos_id'),
			'embarcacaoModelosEditavels' => array(self::HAS_MANY, 'EmbarcacaoModelosEditavel', 'embarcacao_modelos_id'),
			'embarcacoes' => array(self::HAS_MANY, 'Embarcacoes', 'embarcacao_modelos_id'),
			'embarcacoesSeos' => array(self::HAS_MANY, 'EmbarcacoesSeo', 'embarcacao_modelos_id'),
			'tabelaEmbarcacoes' => array(self::HAS_MANY, 'TabelaEmbarcacoes', 'embarcacao_modelos_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'embarcacao_macros_id' => null,
			'embarcacao_fabricantes_id' => null,
			'embarcacao_tipos_id' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'slug' => Yii::t('app', 'Slug'),
			'tamanho' => Yii::t('app', 'Tamanho'),
			'passageiros' => Yii::t('app', 'Passageiros'),
			'acomodacoes' => Yii::t('app', 'Acomodacoes'),
			'comprimento' => Yii::t('app', 'Comprimento'),
			'boca' => Yii::t('app', 'Boca'),
			'calado' => Yii::t('app', 'Calado'),
			'pedireito' => Yii::t('app', 'Pedireito'),
			'pesocasco' => Yii::t('app', 'Pesocasco'),
			'tanquecombustivel' => Yii::t('app', 'Tanquecombustivel'),
			'tanqueagua' => Yii::t('app', 'Tanqueagua'),
			'consumo' => Yii::t('app', 'Consumo'),
			'ncamarotes' => Yii::t('app', 'Ncamarotes'),
			'nbanheiros' => Yii::t('app', 'Nbanheiros'),
			'motor_de_fabrica' => Yii::t('app', 'Motor De Fabrica'),
			'status' => Yii::t('app', 'Status'),
			'embarcacaoFabricantes' => null,
			'embarcacaoMacros' => null,
			'embarcacaoTipos' => null,
			'embarcacaoModelosEditavels' => null,
			'embarcacoes' => null,
			'embarcacoesSeos' => null,
			'tabelaEmbarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);
		$criteria->compare('embarcacao_fabricantes_id', $this->embarcacao_fabricantes_id);
		$criteria->compare('embarcacao_tipos_id', $this->embarcacao_tipos_id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('tamanho', $this->tamanho, true);
		$criteria->compare('passageiros', $this->passageiros);
		$criteria->compare('acomodacoes', $this->acomodacoes);
		$criteria->compare('comprimento', $this->comprimento, true);
		$criteria->compare('boca', $this->boca, true);
		$criteria->compare('calado', $this->calado, true);
		$criteria->compare('pedireito', $this->pedireito, true);
		$criteria->compare('pesocasco', $this->pesocasco, true);
		$criteria->compare('tanquecombustivel', $this->tanquecombustivel, true);
		$criteria->compare('tanqueagua', $this->tanqueagua, true);
		$criteria->compare('consumo', $this->consumo, true);
		$criteria->compare('ncamarotes', $this->ncamarotes);
		$criteria->compare('nbanheiros', $this->nbanheiros);
		$criteria->compare('motor_de_fabrica', $this->motor_de_fabrica, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}