<?php

/**
 * This is the model base class for the table "macros".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Macros".
 *
 * Columns in table "macros" available as properties of the model,
 * followed by relations of table "macros" available as properties of the model.
 *
 * @property integer $id
 * @property string $titulo
 * @property string $alias
 *
 * @property Conteudos[] $conteudoses
 * @property Embarcacoes[] $embarcacoes
 * @property Empresas[] $empresases
 * @property Planos[] $planoses
 */
abstract class BaseMacros extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'macros';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Macros|Macroses', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo, alias', 'required'),
			array('titulo', 'length', 'max'=>45),
			array('alias', 'length', 'max'=>30),
			array('id, titulo, alias', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'conteudoses' => array(self::HAS_MANY, 'Conteudos', 'macros_id'),
			'embarcacoes' => array(self::HAS_MANY, 'Embarcacoes', 'macros_id'),
			'empresases' => array(self::HAS_MANY, 'Empresas', 'macros_id'),
			'planoses' => array(self::HAS_MANY, 'Planos', 'macros_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'alias' => Yii::t('app', 'Alias'),
			'conteudoses' => null,
			'embarcacoes' => null,
			'empresases' => null,
			'planoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('alias', $this->alias, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}