<?php

/**
 * This is the model base class for the table "conteudo_seo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConteudoSeo".
 *
 * Columns in table "conteudo_seo" available as properties of the model,
 * followed by relations of table "conteudo_seo" available as properties of the model.
 *
 * @property integer $id
 * @property integer $conteudos_id
 * @property integer $conteudo_categorias_id
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property integer $follow
 * @property integer $index
 *
 * @property Conteudos $conteudos
 * @property ConteudoCategorias $conteudoCategorias
 */
abstract class BaseConteudoSeo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'conteudo_seo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConteudoSeo|ConteudoSeos', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('conteudos_id, conteudo_categorias_id, follow, index', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>65),
			array('description', 'length', 'max'=>150),
			array('keywords', 'length', 'max'=>250),
			array('conteudos_id, conteudo_categorias_id, title, description, keywords, follow, index', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, conteudos_id, conteudo_categorias_id, title, description, keywords, follow, index', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'conteudos' => array(self::BELONGS_TO, 'Conteudos', 'conteudos_id'),
			'conteudoCategorias' => array(self::BELONGS_TO, 'ConteudoCategorias', 'conteudo_categorias_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'conteudos_id' => null,
			'conteudo_categorias_id' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'keywords' => Yii::t('app', 'Keywords'),
			'follow' => Yii::t('app', 'Follow'),
			'index' => Yii::t('app', 'Index'),
			'conteudos' => null,
			'conteudoCategorias' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('conteudos_id', $this->conteudos_id);
		$criteria->compare('conteudo_categorias_id', $this->conteudo_categorias_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keywords', $this->keywords, true);
		$criteria->compare('follow', $this->follow);
		$criteria->compare('index', $this->index);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}