<?php

/**
 * This is the model base class for the table "acessorio_modelos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AcessorioModelos".
 *
 * Columns in table "acessorio_modelos" available as properties of the model,
 * followed by relations of table "acessorio_modelos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $acessorio_tipos_id
 * @property integer $embarcacao_macros_id
 * @property string $titulo
 * @property integer $status
 *
 * @property AcessorioTipos $acessorioTipos
 * @property EmbarcacaoMacros $embarcacaoMacros
 * @property EmbarcacaoAcessorios[] $embarcacaoAcessorioses
 */
abstract class BaseAcessorioModelos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'acessorio_modelos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AcessorioModelos|AcessorioModeloses', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('acessorio_tipos_id, embarcacao_macros_id, titulo', 'required'),
			array('acessorio_tipos_id, embarcacao_macros_id, status', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>45),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, acessorio_tipos_id, embarcacao_macros_id, titulo, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'acessorioTipos' => array(self::BELONGS_TO, 'AcessorioTipos', 'acessorio_tipos_id'),
			'embarcacaoMacros' => array(self::BELONGS_TO, 'EmbarcacaoMacros', 'embarcacao_macros_id'),
			'embarcacaoAcessorioses' => array(self::HAS_MANY, 'EmbarcacaoAcessorios', 'acessorios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'acessorio_tipos_id' => null,
			'embarcacao_macros_id' => null,
			'titulo' => Yii::t('app', 'Titulo'),
			'status' => Yii::t('app', 'Status'),
			'acessorioTipos' => null,
			'embarcacaoMacros' => null,
			'embarcacaoAcessorioses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('acessorio_tipos_id', $this->acessorio_tipos_id);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}