<?php

/**
 * This is the model base class for the table "empresa_imagens".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmpresaImagens".
 *
 * Columns in table "empresa_imagens" available as properties of the model,
 * followed by relations of table "empresa_imagens" available as properties of the model.
 *
 * @property integer $id
 * @property string $imagem
 * @property integer $empresas_id
 * @property integer $status
 *
 * @property Empresas $empresas
 */
abstract class BaseEmpresaImagens extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresa_imagens';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmpresaImagens|EmpresaImagens', $n);
	}

	public static function representingColumn() {
		return 'imagem';
	}

	public function rules() {
		return array(
			array('imagem, empresas_id, status', 'required'),
			array('empresas_id, status', 'numerical', 'integerOnly'=>true),
			array('imagem', 'length', 'max'=>100),
			array('id, imagem, empresas_id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empresas' => array(self::BELONGS_TO, 'Empresas', 'empresas_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'imagem' => Yii::t('app', 'Imagem'),
			'empresas_id' => null,
			'status' => Yii::t('app', 'Status'),
			'empresas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('imagem', $this->imagem, true);
		$criteria->compare('empresas_id', $this->empresas_id);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}