<?php

/**
 * This is the model base class for the table "ordem_tipos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrdemTipos".
 *
 * Columns in table "ordem_tipos" available as properties of the model,
 * followed by relations of table "ordem_tipos" available as properties of the model.
 *
 * @property integer $id
 * @property string $titulo
 * @property string $alias
 *
 * @property Ordens[] $ordens
 */
abstract class BaseOrdemTipos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ordem_tipos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrdemTipos|OrdemTiposes', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('titulo, alias', 'length', 'max'=>45),
			array('titulo, alias', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, titulo, alias', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ordens' => array(self::HAS_MANY, 'Ordens', 'ordem_tipos_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'alias' => Yii::t('app', 'Alias'),
			'ordens' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('alias', $this->alias, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}