<?php

/**
 * This is the model base class for the table "transacao_planos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TransacaoPlanos".
 *
 * Columns in table "transacao_planos" available as properties of the model,
 * followed by relations of table "transacao_planos" available as properties of the model.
 *
 * @property integer $id
 * @property string $tid
 * @property string $valor
 * @property string $formapagamento
 * @property string $data
 * @property integer $status
 * @property integer $plano_usuarios_id
 * @property integer $usuarios_id
 *
 * @property PlanoUsuarios $planoUsuarios
 * @property Usuarios $usuarios
 */
abstract class BaseTransacaoPlanos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'transacao_planos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TransacaoPlanos|TransacaoPlanoses', $n);
	}

	public static function representingColumn() {
		return 'tid';
	}

	public function rules() {
		return array(
			array('tid, valor, data, status, plano_usuarios_id, usuarios_id', 'required'),
			array('status, plano_usuarios_id, usuarios_id', 'numerical', 'integerOnly'=>true),
			array('tid, formapagamento', 'length', 'max'=>45),
			array('valor', 'length', 'max'=>10),
			array('formapagamento', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, tid, valor, formapagamento, data, status, plano_usuarios_id, usuarios_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'planoUsuarios' => array(self::BELONGS_TO, 'PlanoUsuarios', 'plano_usuarios_id'),
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'tid' => Yii::t('app', 'Tid'),
			'valor' => Yii::t('app', 'Valor'),
			'formapagamento' => Yii::t('app', 'Formapagamento'),
			'data' => Yii::t('app', 'Data'),
			'status' => Yii::t('app', 'Status'),
			'plano_usuarios_id' => null,
			'usuarios_id' => null,
			'planoUsuarios' => null,
			'usuarios' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('tid', $this->tid, true);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('formapagamento', $this->formapagamento, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('plano_usuarios_id', $this->plano_usuarios_id);
		$criteria->compare('usuarios_id', $this->usuarios_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}