<?php

/**
 * This is the model base class for the table "empresas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Empresas".
 *
 * Columns in table "empresas" available as properties of the model,
 * followed by relations of table "empresas" available as properties of the model.
 *
 * @property integer $id
 * @property string $email
 * @property string $razao
 * @property string $tipo
 * @property string $logo
 * @property string $capa
 * @property string $maps
 * @property string $cnpj
 * @property string $telefone1
 * @property integer $estados_id
 * @property integer $cidades_id
 * @property string $cep
 * @property string $endereco
 * @property integer $numero
 * @property string $bairro
 * @property string $fanpage
 * @property string $video
 * @property integer $empresa_categorias_id
 * @property integer $usuarios_id
 * @property integer $macros_id
 * @property integer $status
 * @property integer $destaque
 * @property string $slug
 * @property string $descricao
 * @property string $minidescricao
 *
 * @property EmpresaImagens[] $empresaImagens
 * @property EmpresaSeo[] $empresaSeos
 * @property Cidades $cidades
 * @property EmpresaCategorias $empresaCategorias
 * @property Estados $estados
 * @property Macros $macros
 * @property Usuarios $usuarios
 * @property EmpresasHasEmpresaRecursosAdicionais[] $empresasHasEmpresaRecursosAdicionaises
 * @property EmpresasImpressoes[] $empresasImpressoes
 * @property UsuariosEmbarcacoes[] $usuariosEmbarcacoes
 */
abstract class BaseEmpresas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'empresas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Empresas|Empresases', $n);
	}

	public static function representingColumn() {
		return 'razao';
	}

	public function rules() {
		return array(
			array('razao, empresa_categorias_id, usuarios_id, macros_id, destaque, slug', 'required'),
			array('numero, empresa_categorias_id, usuarios_id, macros_id, status, destaque, embarcacao_macros_id', 'numerical', 'integerOnly'=>true),
			array('email, razao, cnpj, cep, bairro, slug', 'length', 'max'=>45),
			array('logo, capa, maps, endereco, fanpage, minidescricao', 'length', 'max'=>300),
			array('telefone', 'length', 'max'=>20),
			array('video', 'length', 'data_ativacao', 'nomefantasia', 'max'=>150),
			array('descricao', 'safe'),
			array('email, data_ativacao, logo, capa, maps, cnpj, telefone, estados_id, cidades_id, cep, endereco, numero, bairro, fanpage, video, status, descricao, embarcacao_macros_id, minidescricao, plano_usuarios_id, complemento', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, email, data_ativacao, razao, logo, capa, maps, cnpj, telefone, estados_id, cidades_id, cep, endereco, numero, bairro, fanpage, video, empresa_categorias_id, usuarios_id, macros_id, plano_usuarios_id, embarcacao_macros_id, status, destaque, slug, descricao, minidescricao, complemento', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'empresaImagens' => array(self::HAS_MANY, 'EmpresaImagens', 'empresas_id'),
			'empresaSeos' => array(self::HAS_MANY, 'EmpresaSeo', 'empresas_id'),
			'embarcacaoMacros' => array(self::BELONGS_TO, 'EmbarcacaoMacros', 'embarcacao_macros_id'),
			'cidades' => array(self::BELONGS_TO, 'Cidades', 'cidades_id'),
			'empresaCategorias' => array(self::BELONGS_TO, 'EmpresaCategorias', 'empresa_categorias_id'),
			'estados' => array(self::BELONGS_TO, 'Estados', 'estados_id'),
			'macros' => array(self::BELONGS_TO, 'Macros', 'macros_id'),
			'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
			'planoUsuarios' =>array(self::BELONGS_TO, 'PlanoUsuarios', 'plano_usuarios_id'),
			'empresaRecursosAdicionaises' => array(self::MANY_MANY, 'EmpresaRecursosAdicionais', 'empresas_has_empresa_recursos_adicionais(empresas_id, empresa_recursos_adicionais_id)'),
			'empresasImpressoes' => array(self::HAS_MANY, 'EmpresasImpressoes', 'empresas_id'),
			'usuariosEmbarcacoes' => array(self::HAS_MANY, 'UsuariosEmbarcacoes', 'empresas_id'),
		);
	}

	public function pivotModels() {
		return array(
			'empresaRecursosAdicionaises' => 'EmpresasHasEmpresaRecursosAdicionais',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'email' => Yii::t('app', 'Email'),
			'razao' => Yii::t('app', 'Razao'),
			'logo' => Yii::t('app', 'Logo'),
			'capa' => Yii::t('app', 'Capa'),
			'maps' => Yii::t('app', 'Maps'),
			'cnpj' => Yii::t('app', 'Cnpj'),
			'nomefantasia' => Yii::t('app', 'Nome Fantasia'),
			'cliques' => Yii::t('app', 'Cliques'),
			'vertelefone' => Yii::t('app', 'Ver Telefone'),
			'telefone' => Yii::t('app', 'Telefone'),
			'estados_id' => null,
			'cidades_id' => null,
			'embarcacao_macros_id' => null,
			'cep' => Yii::t('app', 'Cep'),
			'endereco' => Yii::t('app', 'Endereco'),
			'numero' => Yii::t('app', 'Numero'),
			'bairro' => Yii::t('app', 'Bairro'),
			'complemento' => Yii::t('app', 'Complemento'),
			'fanpage' => Yii::t('app', 'Fanpage'),
			'video' => Yii::t('app', 'Video'),
			'empresa_categorias_id' => null,
			'usuarios_id' => null,
			'embarcacaoMacros' => null,
			'macros_id' => null,
			'status' => Yii::t('app', 'Status'),
			'destaque' => Yii::t('app', 'Destaque'),
			'slug' => Yii::t('app', 'Slug'),
			'descricao' => Yii::t('app', 'Descricao'),
			'minidescricao' => Yii::t('app', 'Minidescricao'),
			'empresaImagens' => null,
			'empresaSeos' => null,
			'cidades' => null,
			'empresaCategorias' => null,
			'estados' => null,
			'macros' => null,
			'usuarios' => null,
			'empresaRecursosAdicionaises' => null,
			'empresasImpressoes' => null,
			'usuariosEmbarcacoes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('razao', $this->razao, true);
		$criteria->compare('logo', $this->logo, true);
		$criteria->compare('capa', $this->capa, true);
		$criteria->compare('maps', $this->maps, true);
		$criteria->compare('cnpj', $this->cnpj, true);
		$criteria->compare('nomefantasia', $this->nomefatansia, true);
		$criteria->compare('telefone', $this->telefone, true);
		$criteria->compare('estados_id', $this->estados_id);
		$criteria->compare('cidades_id', $this->cidades_id);
		$criteria->compare('cep', $this->cep, true);
		$criteria->compare('endereco', $this->endereco, true);
		$criteria->compare('numero', $this->numero);
		$criteria->compare('bairro', $this->bairro, true);
		$criteria->compare('complemento', $this->complemento, true);
		$criteria->compare('fanpage', $this->fanpage, true);
		$criteria->compare('video', $this->video, true);
		$criteria->compare('empresa_categorias_id', $this->empresa_categorias_id);
		$criteria->compare('usuarios_id', $this->usuarios_id);
		$criteria->compare('macros_id', $this->macros_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('destaque', $this->destaque);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('minidescricao', $this->minidescricao, true);
		$criteria->compare('embarcacao_macros_id', $this->embarcacao_macros_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}