<?php

/**
 * This is the model base class for the table "app_tokens".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AppTokens".
 *
 * Columns in table "app_tokens" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $token
 *
 */
abstract class BaseAppTokens extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'app_tokens';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AppTokens|AppTokens', $n);
	}

	public static function representingColumn() {
		return 'token';
	}

	public function rules() {
		return array(
			array('token', 'safe'),
			array('token', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, token', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'token' => Yii::t('app', 'Token'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('token', $this->token, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}