<?php

/**
 * This is the model base class for the table "embarcacao_recursos_adicionais".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmbarcacaoRecursosAdicionais".
 *
 * Columns in table "embarcacao_recursos_adicionais" available as properties of the model,
 * followed by relations of table "embarcacao_recursos_adicionais" available as properties of the model.
 *
 * @property integer $id
 * @property string $titulo
 * @property string $flag
 * @property string $valor
 * @property integer $status
 *
 * @property EmbarcacoesHasEmbarcacaoRecursosAdicionais[] $embarcacoesHasEmbarcacaoRecursosAdicionaises
 */
abstract class BaseEmbarcacaoRecursosAdicionais extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'embarcacao_recursos_adicionais';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmbarcacaoRecursosAdicionais|EmbarcacaoRecursosAdicionaises', $n);
	}

	public static function representingColumn() {
		return 'titulo';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, status', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>45),
			array('flag', 'length', 'max'=>30),
			array('valor', 'length', 'max'=>10),
			array('titulo, flag, valor, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, titulo, flag, valor, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'embarcacoesHasEmbarcacaoRecursosAdicionaises' => array(self::HAS_MANY, 'EmbarcacoesHasEmbarcacaoRecursosAdicionais', 'embarcacao_recursos_adicionais_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'titulo' => Yii::t('app', 'Titulo'),
			'flag' => Yii::t('app', 'Flag'),
			'valor' => Yii::t('app', 'Valor'),
			'status' => Yii::t('app', 'Status'),
			'embarcacoesHasEmbarcacaoRecursosAdicionaises' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('titulo', $this->titulo, true);
		$criteria->compare('flag', $this->flag, true);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}