<?php

/**
 * This is the model base class for the table "maillings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Maillings".
 *
 * Columns in table "maillings" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $email
 * @property string $data
 * @property string $useragent
 *
 */
abstract class BaseMaillings extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'maillings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Maillings|Maillings', $n);
	}

	public static function representingColumn() {
		return 'email';
	}

	public function rules() {
		return array(
			array('email, data, useragent', 'required'),
			array('email', 'length', 'max'=>100),
			array('id, email, data, useragent', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'email' => Yii::t('app', 'Email'),
			'data' => Yii::t('app', 'Data'),
			'useragent' => Yii::t('app', 'Useragent'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('useragent', $this->useragent, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}