<?php

/**
 * This is the model base class for the table "log_buscas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LogBuscas".
 *
 * Columns in table "log_buscas" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $busca
 * @property string $data
 * @property integer $usuario
 * @property string $ip
 *
 */
abstract class BaseLogBuscas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'log_buscas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LogBuscas|LogBuscases', $n);
	}

	public static function representingColumn() {
		return 'busca';
	}

	public function rules() {
		return array(
			array('data, ip', 'required'),
			array('usuario', 'numerical', 'integerOnly'=>true),
			array('busca', 'length', 'max'=>100),
			array('ip', 'length', 'max'=>45),
			array('usuario', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, busca, data, usuario, ip', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'busca' => Yii::t('app', 'Busca'),
			'data' => Yii::t('app', 'Data'),
			'usuario' => Yii::t('app', 'Usuario'),
			'ip' => Yii::t('app', 'Ip'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('busca', $this->busca, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('usuario', $this->usuario);
		$criteria->compare('ip', $this->ip, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}